### ISSUE TITLE
ver 1で実装するもの

### ISSUE THREAD

**Issue by TomSuzuki** [FUN-AI/MusicServer#1]
- [x] 音楽のアップロード  
- [x] 音楽の再生、停止  
- [ ] プレイリストの管理

**Comment by EbichanOO** [comment]
goのコンパイルしたバイナリを提供しようと思うが、とむとつついの実行環境のOS, アーキテクチャを教えてほしい。次の中のどれ？OS:[android, linux, windows], Arch:[amd64(64bit-x86), 386(32bit-x86), arm(32bit-ARM), arm64(64bit-ARM)] ここにない場合応相談でよろぴく

**Comment by TomSuzuki** [comment]
実行（開発）環境いろいろありすぎる...
開発メイン：Linux（arm64）
サブ：Linux（386）
家メイン：windows（arm64）
（windows 386もあるのでなんでも可）

**Comment by TomSuzuki** [comment]
アップロードどんな感じで実装した？

**Comment by EbichanOO** [comment]
linux arm64でコンパイルしますねぇ。
アップロードでは'file'っていうkeyに対してmp3ファイルをつけて送信すれば複数ファイルアップロードできる(まだmp3チェックはしていない)

**Comment by EbichanOO** [comment]
なんかyoutubeダウンローダーとmp3変換のプログラムを先に作っちゃった

**Comment by TomSuzuki** [comment]
ok

**Comment by TomSuzuki** [comment]
関数の使い方が知りたい...
